version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
